# Generated by Django 5.1.4 on 2024-12-23 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library_blog', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Введите имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Укажите эл.почту ')),
                ('phone_number', models.IntegerField(verbose_name='Введите номер телефона')),
                ('book', models.URLField(verbose_name='Укажите ссылку аудио книги')),
                ('book_buy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_book', to='library_blog.bookmodel')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
